version: '3.9'

services:
  backend:
    build: ./backend
    container_name: app_backend
    platform: linux/amd64
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app/back
    environment:
      - PORT=4000
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=TodoDatabase
      - MYSQL_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4000"]
      timeout: 10s
      retries: 5
    depends_on:
      mysqlDb:
        condition: service_healthy
  frontend:
    build: ./frontend
    container_name: app_frontend
    platform: linux/amd64
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    command: npm start
  mysqlDb:
    image: mysql:8.0.21
    platform: linux/amd64
    container_name: app_mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=12345
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
    cap_add:
     - SYS_NICE